/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2014-04-03 17:05:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.collaba.management.vo.PropertyVO;
import java.util.Collection;
import java.util.Iterator;

public final class searchview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1396544081295L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1396544081295L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table align=\"top\" height=\"70\" width=\"100%\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td height=\"70\" width=\"100%\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title> </title>\r\n");
      out.write("<link href=\"styles.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function clock()\r\n");
      out.write("\t{ \r\n");
      out.write("\tvar dat = new Date();\r\n");
      out.write("\tt = dat.getDate() +\"-\"+ (dat.getMonth()+1) +\"-\"+ dat.getFullYear();\r\n");
      out.write("\tvar hour= dat.getHours();\r\n");
      out.write("\tvar min= dat.getMinutes();\r\n");
      out.write("\tvar sec = dat.getSeconds();\r\n");
      out.write("\tvar temp = \"\" + ((hour > 12) ? hour - 12 :hour) \r\n");
      out.write("\ttemp += ((min < 10) ? \":0\" : \":\") + min\r\n");
      out.write("\ttemp += ((sec < 10) ? \":0\" : \":\") + sec\r\n");
      out.write("\ttemp += (hour >= 12) ? \" PM\" : \" AM\"\r\n");
      out.write("                document.getElementById('clk').innerHTML=t + \" \" + temp;\r\n");
      out.write("//\talert(  document.getElementById('clk').text);\r\n");
      out.write("      \tid = setTimeout(\"clock()\",1000)\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onLoad=\"clock()\">\r\n");
      out.write("<div> \r\n");
      out.write("\t<table id=\"header\" \tcellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td\twidth=\"15%\"><img src=\"images/Logo.jpg\"></td>\r\n");
      out.write("\t\t\t<td class=\"text\" width=\"70%\">Property Management</td>\r\n");
      out.write("\t\t\t<td\twidth=\"15%\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr><td><label id=\"clk\"></label></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td>Call :1-800-000-250</td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td>Welcome  ");
      out.print( session.getAttribute("user") );
      out.write("&nbsp;&nbsp;&nbsp;<a href=\"login.jsp\">Logout<a></td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("<table width=\"100%\" bgcolor=\"#083253\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<table align=\"center\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\">\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"home_mod.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"news.jsp\">News</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"message.jsp\">Messages</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"careers.jsp\">Careers</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"testimonials.jsp\">Testimonials</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"Alliance.jsp\">Alliances</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"blogs.jsp\">Blogs</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"dashboards.jsp\">Dashboard</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"faqs.jsp\">Faq's</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"aboutus.jsp\">About Us</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");


Collection propertylist=(Collection)session.getAttribute("search");

System.out.println("SIZE OF TIMETABLELIST"+propertylist.size());

Iterator iterT=propertylist.iterator();

PropertyVO voT=null;


      out.write('\r');
      out.write('\n');

while(iterT.hasNext())
{
	
       voT=(PropertyVO)iterT.next();


      out.write('\r');
      out.write('\n');
String amenities=voT.getAmenities();
String amenityid=null;
String landmarkid=null;
if(amenities.equals("1"))
			amenityid="Park";
		else if(amenities.equals("2"))
			amenityid="Gym";
		else if(amenities.equals("3"))
			amenityid="Swimming Pool";
		else if(amenities.equals("4"))
			amenityid="Car Parking";
		else if(amenities.equals("5"))
			amenityid="Swimming Pool,Park";
		else if(amenities.equals("6"))
			amenityid="Gym+Park";
		else if(amenities.equals("7"))
			amenityid="Swimming Pool+Gym";
		else if(amenities.equals("8"))
			amenityid="Car parking,Park";
		else if(amenities.equals("9"))
			amenityid="Car Parking,Gym";
		else if(amenities.equals("10"))
			amenityid="Car Parking,Swimming Pool";
		else if(amenities.equals("11"))
			amenityid="Swimming Pool,Gym,Park";
		else if(amenities.equals("12"))
			amenityid="Car Parking,Gym,Park";
		else if(amenities.equals("13"))
			amenityid="Car Parking,Swimming Pool,Park";
		else if(amenities.equals("14"))
			amenityid="Car Parking+Swimming Pool+Park+Gym";
		System.out.println(amenityid);
		
		voT.setAmenities(amenityid);
		String landmark=voT.getLandmark();
		
		if(landmark.equals("1"))
			landmarkid="School";
		else if(landmark.equals("2"))
			landmarkid="Hospital";
		else if(landmark.equals("3"))
			landmarkid="Railway Station";
		else if(landmark.equals("4"))
			landmarkid="Bus Stand";
		else if(landmark.equals("5"))
			landmarkid="School,Hospital";
		else if(landmark.equals("6"))
			landmarkid="School,Railway Station";
		else if(landmark.equals("7"))
			landmarkid="School,Bus Stand";
		else if(landmark.equals("8"))
			landmarkid="Hospital,Railway Station";
		else if(landmark.equals("9"))
			landmarkid="Hospital,Bus Stand";
		else if(landmark.equals("10"))
			landmarkid="Railway Station,Bus Stand";
		else if(landmark.equals("11"))
			landmarkid="School,Hospital,Railway Station";
		else if(landmark.equals("12"))
			landmarkid="School,Railway Station,Bus Stand";
		else if(landmark.equals("13"))
			landmarkid="School,Hospital,Bus Stand";
		else if(landmark.equals("14"))
			landmarkid="Hospital,Railway Station,Bus Stand";
		else if(landmark.equals("15"))
			landmarkid="School,Hospital,Railway Station,Bus Stand";
		else
		{}
		voT.setLandmark(landmarkid);
		
		String propertytypeid=null;
		String property=voT.getPropertytype();
		if(property.equals("1"))
			propertytypeid="Residential";
		else if(property.equals("2"))
			propertytypeid="Commercial";
		else if(property.equals("3"))
			propertytypeid="Agricultural";
		else if(property.equals("4"))
			propertytypeid="Industrial";
		else
		{}
		voT.setPropertytype(propertytypeid);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\" height=\"200\" width=\"100%\">\r\n");
      out.write("\r\n");
      out.write("<tr height=\"10%\">\r\n");
      out.write("\t<th align=\"left\"><font size=\"4\" color=\"white\"><b><u>Properties in ");
      out.print(voT.getCity());
      out.write("</u></b><font></th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr bgcolor=\"#EEEEE5\" height=\"20\">\r\n");
      out.write("\t<td><font size=\"3\" color=\"white\">\r\n");
      out.write("\tProperty address is ");
      out.print(voT.getAdd1());
      out.write(" having plot number ");
      out.print(voT.getPlotno());
      out.write(", and area is ");
      out.print(voT.getSqft());
      out.write(" sqft. Property age is ");
      out.print(voT.getPropertyage());
      out.write(" years and property type is ");
      out.print(voT.getPropertytype());
      out.write(".\r\n");
      out.write("\t Landmarks are : ");
      out.print(voT.getLandmark());
      out.write(" , Amenities :");
      out.print(voT.getAmenities());
      out.write(" and property is ");
      out.print(voT.getFurnishing());
      out.write(". Number of bedrooms ");
      out.print(voT.getBedrooms());
      out.write("\r\n");
      out.write("\t,number of rooms are and  ");
      out.print(voT.getRooms());
      out.write(". Cost of this property is ");
      out.print(voT.getCostrange());
      out.write(".\r\n");
      out.write("\tThe name of the person who handle this property is ");
      out.print(voT.getName());
      out.write(", his contact number is ");
      out.print(voT.getContact());
      out.write(",emial id is ");
      out.print(voT.getEmailid());
      out.write(" and address is ");
      out.print(voT.getAdd2());
      out.write(".\r\n");
      out.write("\t</font></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
}
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<table align=\"bottom\" height=\"50\" width=\"100%\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td height=\"50\" width=\"100%\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Footer</title>\r\n");
      out.write("<body>\r\n");
      out.write("<table id=\"footer\" align=\"center\" bgcolor=\"#2D69A8\" width=\"100%\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\">\r\n");
      out.write("\tcopyright &copy; 2011 Real Estate Management</font>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t<a href=\"terms.jsp\"  target=\"middle\">Terms & Conditions</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;    \r\n");
      out.write("\t<a href=\"privacy.jsp\"  target=\"middle\">Privacy & Policy</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t<a href=\"sitemap.jsp\"  target=\"middle\">Sitemap</a>\r\n");
      out.write(" </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr><td>\r\n");
      out.write("\t<marquee><font color=\"white\">Welcome to  Property Management Portal:  Call us to Advertise for Property Management & Allied Services</font></marquee>\r\n");
      out.write(" </td></tr>\r\n");
      out.write(" </table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
